package com.vcredit.vmc.rules.drools.input;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AntiCheckInput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "计划名称")
    private java.lang.String planName;
    @org.kie.api.definition.type.Label(value = "产品代码")
    private java.lang.String productCode;
    @org.kie.api.definition.type.Label(value = "来源")
    private java.lang.Integer promoteSource;
    @org.kie.api.definition.type.Label(value = "入参步骤")
    private java.lang.String step;
    @org.kie.api.definition.type.Label(value = "当前步骤")
    private java.lang.String currentStep;
    @org.kie.api.definition.type.Label(value = "入参步骤字符")
    private java.lang.Integer stepNumber;
    @org.kie.api.definition.type.Label(value = "当前步骤字符")
    private java.lang.Integer currentStepNumber;
    @org.kie.api.definition.type.Label(value = "额度 保留两位小数")
    private java.math.BigDecimal quota;
    @org.kie.api.definition.type.Label(value = "数据来源")
    private java.lang.String dataSources;
    @org.kie.api.definition.type.Label(value = "前置费用收取标签 Y/N")
    private java.lang.String foreFeeRecvTag;
    @org.kie.api.definition.type.Label(value = "身份证")
    private java.lang.String idNo;

    public AntiCheckInput() {
    }

    public java.lang.String getPlanName() {
        return this.planName;
    }

    public void setPlanName(java.lang.String planName) {
        this.planName = planName;
    }

    public java.lang.String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(java.lang.String productCode) {
        this.productCode = productCode;
    }

    public java.lang.Integer getPromoteSource() {
        return this.promoteSource;
    }

    public void setPromoteSource(java.lang.Integer promoteSource) {
        this.promoteSource = promoteSource;
    }

    public java.lang.String getStep() {
        return this.step;
    }

    public void setStep(java.lang.String step) {
        this.step = step;
    }

    public java.lang.String getCurrentStep() {
        return this.currentStep;
    }

    public void setCurrentStep(java.lang.String currentStep) {
        this.currentStep = currentStep;
    }

    public java.lang.Integer getStepNumber() {
        return this.stepNumber;
    }

    public void setStepNumber(java.lang.Integer stepNumber) {
        this.stepNumber = stepNumber;
    }

    public java.lang.Integer getCurrentStepNumber() {
        return this.currentStepNumber;
    }

    public void setCurrentStepNumber(java.lang.Integer currentStepNumber) {
        this.currentStepNumber = currentStepNumber;
    }

    public java.math.BigDecimal getQuota() {
        return this.quota;
    }

    public void setQuota(java.math.BigDecimal quota) {
        this.quota = quota;
    }

    public java.lang.String getDataSources() {
        return this.dataSources;
    }

    public void setDataSources(java.lang.String dataSources) {
        this.dataSources = dataSources;
    }

    public java.lang.String getForeFeeRecvTag() {
        return this.foreFeeRecvTag;
    }

    public void setForeFeeRecvTag(java.lang.String foreFeeRecvTag) {
        this.foreFeeRecvTag = foreFeeRecvTag;
    }

    public java.lang.String getIdNo() {
        return this.idNo;
    }

    public void setIdNo(java.lang.String idNo) {
        this.idNo = idNo;
    }

    public AntiCheckInput(java.lang.String planName,
                          java.lang.String productCode, java.lang.Integer promoteSource,
                          java.lang.String step, java.lang.String currentStep,
                          java.lang.Integer stepNumber, java.lang.Integer currentStepNumber,
                          java.math.BigDecimal quota, java.lang.String dataSources,
                          java.lang.String foreFeeRecvTag, java.lang.String idNo) {
        this.planName = planName;
        this.productCode = productCode;
        this.promoteSource = promoteSource;
        this.step = step;
        this.currentStep = currentStep;
        this.stepNumber = stepNumber;
        this.currentStepNumber = currentStepNumber;
        this.quota = quota;
        this.dataSources = dataSources;
        this.foreFeeRecvTag = foreFeeRecvTag;
        this.idNo = idNo;
    }

}