package com.vcredit.vmc.rules.drools.output;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AntiCheckOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "结果")
    private java.lang.Boolean result;
    @org.kie.api.definition.type.Label(value = "拒绝原因码")
    private java.lang.String rejectCode;
    @org.kie.api.definition.type.Label(value = "拒绝原因")
    private java.lang.String rejectReason;

    public AntiCheckOutput() {
    }

    public java.lang.Boolean getResult() {
        return this.result;
    }

    public void setResult(java.lang.Boolean result) {
        this.result = result;
    }

    public java.lang.String getRejectCode() {
        return this.rejectCode;
    }

    public void setRejectCode(java.lang.String rejectCode) {
        this.rejectCode = rejectCode;
    }

    public java.lang.String getRejectReason() {
        return this.rejectReason;
    }

    public void setRejectReason(java.lang.String rejectReason) {
        this.rejectReason = rejectReason;
    }

    public AntiCheckOutput(java.lang.Boolean result,
                           java.lang.String rejectCode, java.lang.String rejectReason) {
        this.result = result;
        this.rejectCode = rejectCode;
        this.rejectReason = rejectReason;
    }

}