package com.wjpspace.droolstemplete.entity;

import lombok.Data;

/**
 * This class was automatically generated by the data modeler tool.
 * @author weijupeng
 */
@Data
public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;


    private Long id;
    private Integer age;
    private String name;



    /**
     * 是否需要进行下一步操作
     * 第一个规则文件执行完为true表示通过第一个规则文件 需要执行第二个规则文件
     * 第二个规则文件执行完为true表示需要被推送到电销
     */
    private Boolean valid;

    /**
     * 之前的状态
     */
    private Integer step;
    /**
     * 当前状态
     */
    private Integer currentStep;


}