package com.wjpspace.droolstemplete.entity;

import lombok.Data;

/**
 * This class was automatically generated by the data modeler tool.
 * @author weijupeng
 */
@Data
public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;


    private Long id;
    private Integer age;
    private String name;



    /**
     * 是否需要推送到电销  true需要 false不需要
     */
    private Boolean valid;

    /**
     * 之前的状态
     */
    private Integer step;
    /**
     * 当前状态
     */
    private Integer currentStep;


}