package createEndLabelChar;
import com.vcredit.vmc.rules.fact.TaskNoGetLabelAndPlanFact;
import java.util.Random;

//331需求创建随机标签符
function String createLabelLastChar331(){
        int nextInt = new Random().nextInt(100);

        if (0 < nextInt && nextInt <= 30) {
            return "A";
        }
        if (30 < nextInt && nextInt <= 60) {
            return "B";
        }
        if (60 < nextInt && nextInt <= 90) {
            return "C";
        }
        if (90 < nextInt && nextInt <= 98) {
            return "D";
        }
        else {
            return "E";
        }
}


//333需求创建随机标签符
function String createLabelLastChar333(){
        int nextInt = new Random().nextInt(100);

        if (0 < nextInt && nextInt <= 30) {
            return "A";
        }
        if (30 < nextInt && nextInt <= 35) {
            return "B";
        }
        if (35 < nextInt && nextInt <= 98) {
            return "C";
        }
        else {
            return "D";
        }
}

rule "createEndLabelCharWhen333"
salience 2000
no-loop true
    when
    $fact:TaskNoGetLabelAndPlanFact(taskNo.equals("PM000002"))
    then
    $fact.setEndLabelChar(createLabelLastChar333());
    update($fact)
end

rule "createEndLabelCharWhen331"
salience 2000
no-loop true
    when
    $fact:TaskNoGetLabelAndPlanFact(taskNo.equals("PM000003"))
    then
    $fact.setEndLabelChar(createLabelLastChar331());
    update($fact)
end
