package sms331Rule;
import com.vcredit.vmc.rules.fact.TaskNoGetLabelAndPlanFact
import java.util.ArrayList
import java.util.List


//331需求 E为不营销组
rule "noPromotion"
no-loop true
salience 880
when
    $input:TaskNoGetLabelAndPlanFact(promoteTasksLabel == taskNo+"E" )
then
    ArrayList<String> planNames = new ArrayList<>();
    $input.setPlanNames(planNames);
    $input.setIsSendTaskLabel(false);
    retract($input);
end



//对照组D  不发短信
rule "getPlandsWhenTableD"
no-loop true
salience 870
when
     $input:TaskNoGetLabelAndPlanFact(promoteTasksLabel == (taskNo+"D"))
then
    ArrayList<String> planNames = new ArrayList<>();
    planNames.add("telemarketing_1H");
    $input.setPlanNames(planNames);
    $input.setIsSendTaskLabel(false);
    retract($input);
end

//A 注册 B 授信 C/X 注册或授信  既发短息 也推电销
rule "getPlandsWhenSmsAndTele"
no-loop true
salience 860
when
  $input:TaskNoGetLabelAndPlanFact(
  (promoteTasksLabel == (taskNo+"A") && eventType == ("REGISTER"))    ||
  (promoteTasksLabel==(taskNo+"B")&& eventType==("APPLYAUTH_1"))  ||
  (promoteTasksLabel==(taskNo+"C")&&( eventType==("APPLYAUTH_1") || eventType==("REGISTER"))) ||
  (promoteTasksLabel==(taskNo+"X")&&( eventType==("APPLYAUTH_1") || eventType==("REGISTER")))
  )
then
ArrayList<String> planNames = new ArrayList<>();
    planNames.add("telemarketing_1H");
    planNames.add("sms_10M");
    $input.setPlanNames(planNames);
    $input.setIsSendTaskLabel(false);
    retract($input);
 end

//其他情况下 默认走电销
rule "getPlandsWhenTableANotRegister"
no-loop true
salience 850
when
     $input:TaskNoGetLabelAndPlanFact()
then
    ArrayList<String> planNames = new ArrayList<>();
    planNames.add("telemarketing_1H");
    $input.setPlanNames(planNames);
    $input.setIsSendTaskLabel(false);
    retract($input);
end








