package tele333Rule;
import com.vcredit.vmc.rules.fact.TaskNoGetLabelAndPlanFact
import java.util.ArrayList
import java.util.List



//不营销组 D
rule "noPromotion"
no-loop true

salience 880
when
    $input:TaskNoGetLabelAndPlanFact(promoteTasksLabel != taskNo+"D" )
then
    ArrayList<String> planNames = new ArrayList<>();
    planNames.add("telemarketing_1H");
    $input.setPlanNames(planNames);
    $input.setIsSendTaskLabel(true);
    retract($input);
end








